enviroment: "local"
database:
    driverName: postgres
    dsn: "postgres://postgres:admin@localhost/db?sslmode=disable"

httpServer:
    address: "localhost:10001"
    timeout: 4s
    idleTimeout: 60s